In [43]:
import pandas as pd

In [44]:
df_sent = pd.read_csv("../data/articles_loc_coor_sent.csv")

In [42]:
df_sent.columns

Index(['title', 'link', 'description', 'published', 'city', 'state_name',
       'county_name', 'lat', 'lng', 'roberta_title', 'roberta_description',
       'roberta_title_label', 'roberta_title_score', 'roberta_desc_label',
       'roberta_desc_score'],
      dtype='object')

In [45]:
df_sent.head()

,Unnamed: 0,title,link,description,published,city,state_name,county_name,lat,lng,roberta_title,roberta_description,roberta_title_label,roberta_title_score,roberta_desc_label,roberta_desc_score
0,0,In pictures: Isle's ancient finds,http://www.bbc.co.uk/news/uk-scotland-highland...,Green marble from Greece among ancient finds o...,"Sun, 19 Aug 2012 08:21:03 GMT",Isle,Minnesota,Mille Lacs,46.1389,-93.4592,"('neutral', 0.7356777191162109)","('neutral', 0.8514605164527893)",neutral,0.735678,neutral,0.851461
1,1,Mass burials at ancient Isle site,http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,Archaeologists on Orkney are investigating wha...,"Thu, 02 Dec 2010 10:03:56 GMT",Isle,Minnesota,Mille Lacs,46.1389,-93.4592,"('neutral', 0.8756237626075745)","('neutral', 0.9222922921180725)",neutral,0.875624,neutral,0.922292
2,2,'Mutant rats' immune to poisons,http://www.bbc.co.uk/news/uk-england-19974261#...,An increasing number of rats in parts of the w...,"Wed, 17 Oct 2012 08:57:35 GMT",England,Arkansas,Lonoke,34.5454,-91.9675,"('neutral', 0.814943253993988)","('neutral', 0.6123915910720825)",neutral,0.814943,neutral,0.612392
3,3,Court battle on badger cull fails,http://www.bbc.co.uk/news/science-environment-...,The Badger Trust has lost its Court of Appeal ...,"Tue, 11 Sep 2012 15:57:30 GMT",England,Arkansas,Lonoke,34.5454,-91.9675,"('neutral', 0.5443053841590881)","('negative', 0.8269901871681213)",neutral,0.544305,negative,0.826990
4,4,No English badger cull this year,http://www.bbc.co.uk/go/rss/int/news/-/news/uk...,There will be no culling of badgers in England...,"Tue, 19 Jul 2011 14:18:48 GMT",England,Arkansas,Lonoke,34.5454,-91.9675,"('neutral', 0.6378656029701233)","('neutral', 0.7292953133583069)",neutral,0.637866,neutral,0.729295

In [46]:
df_sent.drop(columns = 'Unnamed: 0', axis = 1, inplace = True)

In [57]:
df_sent_filtered = df_sent.loc[df_sent['city']!='England']
df_sent_filtered = df_sent_filtered.loc[df_sent_filtered['city']!='Russia']
df_sent_filtered = df_sent_filtered.loc[df_sent_filtered['roberta_desc_label']=='negative']

In [58]:
df_sent_filtered.shape

(61, 15)

In [60]:
df_sent_filtered.head(60)

,title,link,description,published,city,state_name,county_name,lat,lng,roberta_title,roberta_description,roberta_title_label,roberta_title_score,roberta_desc_label,roberta_desc_score
201,VIDEO: Bleak future for Tripoli zoo animals?,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,Staff say money to feed the hundreds of animal...,"Sat, 31 Dec 2011 05:39:54 GMT",Tripoli,Iowa,Bremer,42.8083,-92.2578,"('negative', 0.7727240920066833)","('negative', 0.6630409955978394)",negative,0.772724,negative,0.663041
287,Shell protesters appear in court,http://www.bbc.co.uk/news/uk-scotland-edinburg...,"Eight Greenpeace supporters, arrested after de...","Tue, 17 Jul 2012 14:56:44 GMT",Edinburgh,Indiana,Johnson,39.3509,-85.9625,"('neutral', 0.6826146245002747)","('negative', 0.5958563089370728)",neutral,0.682615,negative,0.595856
291,Zoo calls halt to penguin parade,http://www.bbc.co.uk/go/rss/int/news/-/news/uk...,The world famous penguin parade at Edinburgh z...,"Thu, 01 Mar 2012 17:21:16 GMT",Edinburgh,Indiana,Johnson,39.3509,-85.9625,"('neutral', 0.6941623091697693)","('negative', 0.7406460046768188)",neutral,0.694162,negative,0.740646
298,Oklahoma drought kindles spectre of 1930s 'Dus...,http://www.bbc.co.uk/news/science-environment-...,Oklahoma drought kindles spectre of 1930s crisis,"Wed, 02 Jul 2014 21:49:23 GMT",Oklahoma,Pennsylvania,Clearfield,41.1100,-78.7356,"('neutral', 0.6125888824462891)","('negative', 0.7424187064170837)",neutral,0.612589,negative,0.742419
315,BP sues for $40bn over Gulf spill,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,"BP sues Transocean, the owner of the oil rig t...","Thu, 21 Apr 2011 01:10:22 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.5207224488258362)","('negative', 0.6449320316314697)",negative,0.520722,negative,0.644932
320,AUDIO: Picture could 'hardly be worse' after G...,http://news.bbc.co.uk/go/rss/int/news/-/today/...,Almost a year since the Gulf of Mexico oil spi...,"Mon, 21 Feb 2011 08:12:32 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.8337116837501526)","('negative', 0.6868889331817627)",negative,0.833712,negative,0.686889
321,Gulf spill evidence 'destroyed',http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,Oil giant BP accuses services firm Halliburton...,"Tue, 06 Dec 2011 06:23:17 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.5985581278800964)","('negative', 0.8735103607177734)",negative,0.598558,negative,0.873510
322,VIDEO: Plans to improve Gulf water technology,http://www.bbc.co.uk/news/business-19769041#sa...,The entire Gulf region is reliant on desalinat...,"Sat, 29 Sep 2012 09:40:35 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('neutral', 0.5342689156532288)","('negative', 0.7267799377441406)",neutral,0.534269,negative,0.726780
324,Gulf of understanding,http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,Deepwater Horizon may be the biggest accidenta...,"Tue, 3 Aug 2010 16:57:08 +0000",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('neutral', 0.5535933375358582)","('negative', 0.8457225561141968)",neutral,0.553593,negative,0.845723
327,The cap used to slow the Gulf oil leak,http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,As UK MPs cast doubt on Britain's ability to d...,"Thu, 06 Jan 2011 17:03:46 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('neutral', 0.8364479541778564)","('negative', 0.6405200958251953)",neutral,0.836448,negative,0.640520
332,Blame shared over Gulf oil spill,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,"A US federal report finds BP, Transocean and H...","Wed, 14 Sep 2011 21:24:22 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.7613800764083862)","('negative', 0.9068414568901062)",negative,0.761380,negative,0.906841
333,Feeding frenzy,http://www.bbc.co.uk/go/rss/int/news/-/news/bu...,Ex-BP boss admits firm was ill-equipped for Gu...,"Tue, 09 Nov 2010 00:07:26 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('neutral', 0.5359739065170288)","('negative', 0.8146810531616211)",neutral,0.535974,negative,0.814681
334,BP 'not prepared' for Gulf spill,http://www.bbc.co.uk/go/rss/int/news/-/news/bu...,Ex-BP boss admits firm was ill-equipped for Gu...,"Tue, 09 Nov 2010 00:07:26 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.6586589813232422)","('negative', 0.8146810531616211)",negative,0.658659,negative,0.814681
335,BP cements damaged Gulf oil well,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,BP finishes pumping cement into the top of its...,"Thu, 5 Aug 2010 20:50:58 +0000",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.687093198299408)","('negative', 0.6569162011146545)",negative,0.687093,negative,0.656916
338,Gulf oil disaster trial delayed,http://www.bbc.co.uk/go/rss/int/news/-/news/bu...,The civil trial over the 2010 Deepwater Horizo...,"Sun, 26 Feb 2012 21:54:42 GMT",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('negative', 0.7707942724227905)","('negative', 0.5576878786087036)",negative,0.770794,negative,0.557688
339,BP pumping cement into Gulf well,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,BP starts pumping cement into the top of its d...,"Thu, 5 Aug 2010 16:19:44 +0000",Gulf,North Carolina,Chatham,35.5597,-79.2805,"('neutral', 0.8569974303245544)","('negative', 0.6076412796974182)",neutral,0.856997,negative,0.607641
346,Warning over North Sea oil cash,http://www.bbc.co.uk/news/uk-scotland-scotland...,The value of North Sea oil to Scotland's econo...,"Thu, 20 Dec 2012 00:13:08 GMT",North Sea,New York,Suffolk,40.9330,-72.4047,"('neutral', 0.5920818448066711)","('negative', 0.6705145239830017)",neutral,0.592082,negative,0.670515
347,AUDIO: Shell 'deeply regret' North Sea oil spill,http://news.bbc.co.uk/go/rss/int/news/-/today/...,"Glen Cayley, technical director of Shell's exp...","Tue, 16 Aug 2011 07:43:38 GMT",North Sea,New York,Suffolk,40.9330,-72.4047,"('negative', 0.7908028364181519)","('negative', 0.7142643332481384)",negative,0.790803,negative,0.714264
353,Gas leak platform flare 'burning',http://www.bbc.co.uk/go/rss/int/news/-/news/uk...,A flame is still burning above an evacuated No...,"Wed, 28 Mar 2012 18:17:46 GMT",North Sea,New York,Suffolk,40.9330,-72.4047,"('negative', 0.6290870308876038)","('negative', 0.6703351736068726)",negative,0.629087,negative,0.670335
355,£19bn to dismantle North Sea rigs,http://www.bbc.co.uk/go/rss/int/news/-/news/uk...,The cost of dismantling North Sea oil and gas ...,"Tue, 05 Oct 2010 07:17:52 GMT",North Sea,New York,Suffolk,40.9330,-72.4047,"('neutral', 0.8114582896232605)","('negative', 0.5652015805244446)",neutral,0.811458,negative,0.565202
358,New York 'at risk' as seas rise,http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,New York is set to be a major loser as a resul...,"Fri, 08 Apr 2011 12:00:28 GMT",New York,New York,Queens,40.6943,-73.9249,"('neutral', 0.7084051966667175)","('negative', 0.8387162685394287)",neutral,0.708405,negative,0.838716
361,Lab rodents drowned in NY floods,http://www.bbc.co.uk/news/science-environment-...,Thousands of lab rodents have drowned after st...,"Thu, 01 Nov 2012 15:43:51 GMT",New York,New York,Queens,40.6943,-73.9249,"('negative', 0.5308859944343567)","('negative', 0.8034924864768982)",negative,0.530886,negative,0.803492
367,Sandy: New York devastation mapped,http://www.bbc.co.uk/news/world-us-canada-2013...,Maps and images showing the damage caused by H...,"Tue, 30 Oct 2012 18:32:04 GMT",New York,New York,Queens,40.6943,-73.9249,"('neutral', 0.7545174956321716)","('negative', 0.6382957100868225)",neutral,0.754517,negative,0.638296
378,Shark found on New York subway,http://www.bbc.co.uk/news/world-us-canada-2361...,"New York City's subway, no stranger to exotic ...","Wed, 07 Aug 2013 21:05:13 GMT",New York,New York,Queens,40.6943,-73.9249,"('neutral', 0.8699946999549866)","('negative', 0.5445064902305603)",neutral,0.869995,negative,0.544506
384,VIDEO: Crocs to be artificially inseminated,http://www.bbc.co.uk/news/science-environment-...,Crocodiles are being artificially inseminated ...,"Tue, 25 Sep 2012 17:04:02 GMT",Queensland,Maryland,Prince George's,38.8019,-76.7855,"('neutral', 0.6902037858963013)","('negative', 0.8183740377426147)",neutral,0.690204,negative,0.818374
385,Flood victims?,http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,Will the Queensland flood waters' toxic cargo ...,"Fri, 14 Jan 2011 12:36:25 GMT",Queensland,Maryland,Prince George's,38.8019,-76.7855,"('neutral', 0.8023157715797424)","('negative', 0.6658068299293518)",neutral,0.802316,negative,0.665807
387,Cyclone unleashed on Queensland,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,Powerful winds and driving rains pound the nor...,"Wed, 02 Feb 2011 20:09:36 GMT",Queensland,Maryland,Prince George's,38.8019,-76.7855,"('negative', 0.581653356552124)","('negative', 0.5338440537452698)",negative,0.581653,negative,0.533844
394,Farmland birds show rapid decline,http://www.bbc.co.uk/news/science-environment-...,Farmland birds are at their lowest levels sinc...,"Thu, 23 Oct 2014 14:39:14 GMT",Farmland,Indiana,Randolph,40.1895,-85.1273,"('negative', 0.637130081653595)","('negative', 0.7892306447029114)",negative,0.637130,negative,0.789231
395,VIDEO: Farmland birds show rapid decline,http://www.bbc.co.uk/news/science-environment-...,Farmland birds are at their lowest levels sinc...,"Thu, 23 Oct 2014 18:57:19 GMT",Farmland,Indiana,Randolph,40.1895,-85.1273,"('negative', 0.6517814993858337)","('negative', 0.7892306447029114)",negative,0.651781,negative,0.789231
401,Bolivia Amazon road march resumes,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,Indigenous protesters in Bolivia resume their ...,"Sat, 01 Oct 2011 22:31:33 GMT",Bolivia,North Carolina,Brunswick,34.0699,-78.1472,"('neutral', 0.866548478603363)","('negative', 0.5637915134429932)",neutral,0.866548,negative,0.563792
410,VIDEO: Footage captures 'cloud' of starlings,http://www.bbc.co.uk/news/uk-26387395#sa-ns_mc...,Residents in Hereford say they are being plagu...,"Fri, 28 Feb 2014 15:48:16 GMT",Hereford,Texas,Deaf Smith,34.8225,-102.4001,"('neutral', 0.9055725932121277)","('negative', 0.8390506505966187)",neutral,0.905573,negative,0.839051
411,Lower Ninth five years after Katrina,http://news.bbc.co.uk/go/rss/int/news/-/1/hi/p...,The Lower Ninth Ward of New Orleans was hit pa...,"Thu, 26 Aug 2010 23:58:32 GMT",New Orleans,Louisiana,Orleans,30.0687,-89.9288,"('neutral', 0.5867184400558472)","('negative', 0.5115200281143188)",neutral,0.586718,negative,0.511520
413,Beached whale was unusual species,http://www.bbc.co.uk/news/uk-england-tyne-1975...,A female whale put down in Northumberland was ...,"Fri, 28 Sep 2012 15:05:32 GMT",Northumberland,Pennsylvania,Northumberland,40.8966,-76.7933,"('neutral', 0.7368884682655334)","('negative', 0.7256513237953186)",neutral,0.736888,negative,0.725651
419,Australia protests over shark 'cull',http://www.bbc.co.uk/news/world-asia-25603646#...,Thousands of people take to the beaches to pro...,"Sat, 04 Jan 2014 13:15:59 GMT",Perth,North Dakota,Towner,48.7148,-99.4582,"('negative', 0.6977459788322449)","('negative', 0.7303328514099121)",negative,0.697746,negative,0.730333
430,VIDEO: 'Like throwing a snowball at the Sun',http://www.bbc.co.uk/news/science-environment-...,Comet Ison seems to have been destroyed in its...,"Thu, 28 Nov 2013 21:19:18 GMT",Sun,Louisiana,St. Tammany,30.6489,-89.9070,"('neutral', 0.8818756341934204)","('negative', 0.61599200963974)",neutral,0.881876,negative,0.615992
431,VIDEO: Has the Sun gone to sleep?,http://www.bbc.co.uk/news/science-environment-...,Scientists are saying that the Sun is in a pha...,"Fri, 17 Jan 2014 05:57:58 GMT",Sun,Louisiana,St. Tammany,30.6489,-89.9070,"('neutral', 0.9497807621955872)","('negative', 0.5601897835731506)",neutral,0.949781,negative,0.560190
444,Parker Solar Probe: Nasa's Sun mission smashes...,https://www.bbc.co.uk/news/science-environment...,"America's audacious mission to ""touch the Sun""...","Tue, 30 Oct 2018 09:58:28 GMT",Sun,Louisiana,St. Tammany,30.6489,-89.9070,"('neutral', 0.73931884765625)","('negative', 0.646483302116394)",neutral,0.739319,negative,0.646483
451,Belfast lizard numbers 'devastated',http://www.bbc.co.uk/news/uk-northern-ireland-...,A newly-discovered population of lizards has b...,"Thu, 13 Jun 2013 05:49:31 GMT",Belfast,Maine,Waldo,44.4279,-69.0325,"('negative', 0.7791966199874878)","('negative', 0.7929806113243103)",negative,0.779197,negative,0.792981
455,Meet Belfast's young climate change protesters,https://www.bbc.co.uk/news/uk-northern-ireland...,Young people all over the world are walking ou...,"Sat, 25 May 2019 06:21:40 GMT",Belfast,Maine,Waldo,44.4279,-69.0325,"('neutral', 0.8277071118354797)","('negative', 0.6388779282569885)",neutral,0.827707,negative,0.638878
456,Birdsong phone apps 'harming' birds,http://www.bbc.co.uk/news/uk-england-dorset-22...,"The ""harmful misuse"" of mobile phone apps that...","Wed, 12 Jun 2013 07:40:45 GMT",Birdsong,Arkansas,Mississippi,35.4610,-90.2598,"('negative', 0.5383761525154114)","('negative', 0.7319160103797913)",negative,0.538376,negative,0.731916
457,'Black widow' scare at airbase,http://www.bbc.co.uk/news/uk-england-suffolk-1...,Buildings at an air base in Suffolk are closed...,"Mon, 15 Oct 2012 13:09:29 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('neutral', 0.6174588203430176)","('negative', 0.5128631591796875)",neutral,0.617459,negative,0.512863
458,Rats 'eat' part of woman's car,http://www.bbc.co.uk/news/uk-england-suffolk-2...,"Rats ""eat"" part of a Suffolk woman's car causi...","Thu, 24 Jan 2013 09:17:58 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('negative', 0.6804575324058533)","('negative', 0.8794158697128296)",negative,0.680458,negative,0.879416
461,Whale dies after beaching on bank,http://www.bbc.co.uk/news/uk-england-suffolk-1...,"A young fin whale, 10m (33ft) in length, dies ...","Mon, 01 Oct 2012 11:37:38 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('negative', 0.599729061126709)","('negative', 0.6451684236526489)",negative,0.599729,negative,0.645168
462,Barn owl boxes stolen and vandalised,http://www.bbc.co.uk/news/uk-england-suffolk-2...,Five barn owl boxes which are part of a Suffol...,"Thu, 19 Jun 2014 12:12:50 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('negative', 0.8205952644348145)","('negative', 0.8373158574104309)",negative,0.820595,negative,0.837316
466,Fears that ash disease has spread,http://www.bbc.co.uk/news/uk-england-suffolk-2...,Symptoms of Chalara dieback are spotted on ash...,"Fri, 26 Oct 2012 17:08:52 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('negative', 0.8079224824905396)","('negative', 0.49618202447891235)",negative,0.807922,negative,0.496182
470,The nuclear fight for Sizewell on Suffolk's coast,https://www.bbc.co.uk/news/business-48828820,The nuclear industry says new plants are essen...,"Sun, 07 Jul 2019 00:27:39 GMT",Suffolk,Virginia,Suffolk,36.6953,-76.6398,"('neutral', 0.8929838538169861)","('negative', 0.528706431388855)",neutral,0.892984,negative,0.528706
472,Chile rejects hydro-electric project,http://www.bbc.co.uk/news/world-latin-america-...,The Chilean government has rejected a huge hyd...,"Tue, 10 Jun 2014 17:47:59 GMT",Patagonia,Arizona,Santa Cruz,31.5436,-110.7478,"('negative', 0.6267767548561096)","('negative', 0.8087902069091797)",negative,0.626777,negative,0.808790
476,Chile astronomer murder charges,http://www.bbc.co.uk/news/world-latin-america-...,A Chilean man is charged with murdering leadin...,"Fri, 11 May 2012 23:34:34 GMT",Santiago,Washington,Grays Harbor,47.2975,-124.2327,"('negative', 0.674258291721344)","('negative', 0.7925056219100952)",negative,0.674258,negative,0.792506
478,VIDEO: Secrets in Herculaneum's sewers,http://www.bbc.co.uk/news/world-europe-2199612...,Herculaneum was destroyed by the eruption of M...,"Mon, 01 Apr 2013 19:23:13 GMT",Herculaneum,Missouri,Jefferson,38.2579,-90.3948,"('neutral', 0.9114079475402832)","('negative', 0.6773843765258789)",neutral,0.911408,negative,0.677384
484,Recycling wars in San Francisco,http://www.bbc.co.uk/go/rss/int/news/-/news/ma...,Criminals cashing in by stealing cans and bottles,"Tue, 31 Jan 2012 11:55:32 GMT",San Francisco,California,San Francisco,37.7558,-122.4449,"('neutral', 0.8264139890670776)","('negative', 0.6757929921150208)",neutral,0.826414,negative,0.675793
486,Hundreds flee Nicaragua volcano,http://www.bbc.co.uk/news/world-latin-america-...,Nicaraguan authorities order the evacuation of...,"Thu, 27 Dec 2012 08:14:18 GMT",San Cristobal,New Mexico,Taos,36.6101,-105.6319,"('neutral', 0.5197248458862305)","('negative', 0.612774133682251)",neutral,0.519725,negative,0.612774
489,Fish talks bring in tough quotas,http://www.bbc.co.uk/go/rss/int/news/-/news/uk...,Scottish fishermen face deep cuts in quotas fo...,"Wed, 15 Dec 2010 07:36:43 GMT",Brussels,Illinois,Calhoun,38.9483,-90.5887,"('negative', 0.5093112587928772)","('negative', 0.5694633722305298)",negative,0.509311,negative,0.569463
495,Nightingales 'could become extinct in Hampshire',https://www.bbc.co.uk/news/uk-england-hampshir...,A wildlife trust is warning the species could ...,"Fri, 14 Sep 2018 23:26:11 GMT",Hampshire,Illinois,Kane,42.1124,-88.5118,"('neutral', 0.5503156185150146)","('negative', 0.6529568433761597)",neutral,0.550316,negative,0.652957
503,Everest pioneers 'hit by storm',http://www.bbc.co.uk/go/rss/int/news/-/news/sc...,An extreme storm may have contributed to the d...,"Tue, 3 Aug 2010 19:14:47 +0000",Everest,Kansas,Brown,39.6770,-95.4248,"('neutral', 0.8068357706069946)","('negative', 0.5715652108192444)",neutral,0.806836,negative,0.571565
505,Crackdown on Everest mountaineers,http://www.bbc.co.uk/news/science-environment-...,Expeditions on Mount Everest will be more clos...,"Fri, 02 Aug 2013 06:15:55 GMT",Everest,Kansas,Brown,39.6770,-95.4248,"('neutral', 0.8400738835334778)","('negative', 0.5410175919532776)",neutral,0.840074,negative,0.541018
512,Oyster beds hit by BP oil spill,http://news.bbc.co.uk/go/rss/int/news/-/1/hi/p...,The period between Thanksgiving and Christmas ...,"Thu, 16 Dec 2010 22:42:58 GMT",Louisiana,Missouri,Pike,39.4413,-91.0626,"('neutral', 0.5124081969261169)","('negative', 0.5805374979972839)",neutral,0.512408,negative,0.580537
514,BP oil spill: Louisiana ruin remains,http://www.bbc.co.uk/go/rss/int/news/-/news/wo...,The effects of the BP oil spill still linger i...,"Sat, 03 Mar 2012 04:02:07 GMT",Louisiana,Missouri,Pike,39.4413,-91.0626,"('negative', 0.8793550133705139)","('negative', 0.8330166935920715)",negative,0.879355,negative,0.833017
518,Aussie bees fight 'hive wars',http://www.bbc.co.uk/news/science-environment-...,Bee colonies in Brisbane are waging war for mo...,"Tue, 21 Oct 2014 10:44:45 GMT",Brisbane,California,San Mateo,37.6902,-122.4021,"('neutral', 0.733568012714386)","('negative', 0.569614589214325)",neutral,0.733568,negative,0.569615
521,VIDEO: More means less for Maine lobstermen,http://www.bbc.co.uk/news/world-us-canada-2433...,Why Maine's industry is threatened by climate ...,"Tue, 01 Oct 2013 23:20:52 GMT",Maine,Wisconsin,Marathon,45.0497,-89.6817,"('neutral', 0.6708776354789734)","('negative', 0.7984686493873596)",neutral,0.670878,negative,0.798469
529,Marine zone decision 'staggering',http://www.bbc.co.uk/news/uk-england-hampshire...,A wildlife trust criticises the decision not t...,"Tue, 22 Jan 2013 06:08:45 GMT",Marine,Illinois,Madison,38.7868,-89.7789,"('negative', 0.6459630131721497)","('negative', 0.5529472231864929)",negative,0.645963,negative,0.552947

In [63]:
df_article_values = df_sent_filtered['state_name'].value_counts().reset_index()

In [64]:
df_article_values

        state_name  count
0   North Carolina     13
1         New York      8
2         Virginia      6
3        Louisiana      4
4          Indiana      4
5         Maryland      3
6         Illinois      3
7         Missouri      3
8       California      2
9     Pennsylvania      2
10          Kansas      2
11           Maine      2
12            Iowa      1
13       Wisconsin      1
14      New Mexico      1
15        Arkansas      1
16      Washington      1
17         Arizona      1
18    North Dakota      1
19           Texas      1
20        Oklahoma      1

In [65]:
df_article_values.to_csv("../data/df_article_counts_by_state.csv", index = False)